window.__WEDDING_CODE=(window.__WEDDING_CODE||'')+String.raw`(function(){'use strict';
const STORAGE_KEY='mk-wedding-control-v1',ROOM_KEY='mk-wedding-shared-room-v1',THEME_KEY='mk-wedding-theme-v4',AUTHOR_KEY='mk-wedding-chat-author-v1',API='https://jsonblob.com/api/jsonBlob';
const routes={dashboard:['Обзор','Свадебный бюджет и подготовка'],expenses:['Расходы','Подрядчики, предоплаты и остатки'],guests:['Гости','Семьи, люди и подтверждения'],purchases:['Покупки','Что нужно купить до свадьбы'],chat:['Чат','Сообщения Марата и Карины'],settings:['Настройки','Данные, тема и общий доступ']};
const svg=(p)=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+p+'</svg>';
const icons={home:svg('<path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/>'),wallet:svg('<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18"/>'),people:svg('<circle cx="9" cy="7" r="4"/><path d="M2 21a7 7 0 0 1 14 0M17 8a3 3 0 0 1 0 6M22 21a5 5 0 0 0-4-4.5"/>'),check:svg('<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>'),message:svg('<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/>'),settings:svg('<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 1 1-14 0 7 7 0 0 1 14 0z"/>'),sun:svg('<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>'),moon:svg('<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8z"/>'),plus:svg('<path d="M12 5v14M5 12h14"/>'),share:svg('<path d="M12 3v12M7 8l5-5 5 5"/><path d="M5 13v7h14v-7"/>'),person:svg('<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>'),trash:svg('<path d="M3 6h18M8 6V4h8v2M6 6l1 15h10l1-15"/>'),send:svg('<path d="m22 2-7 20-4-9-9-4z"/><path d="M22 2 11 13"/>')};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),num=v=>Math.max(0,Number(String(v==null?'':v).replace(/\s/g,'').replace(',','.'))||0),money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(num(v)),esc=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function defaultState(){return{version:4,settings:{couple:'Марат и Карина',weddingDate:'2026-08-25',budget:1000000},expenses:[],guests:[],purchases:[],chat:[],createdAt:Date.now()}}
function member(name,type,status){return{id:uid(),name:name||'Гость',type:type==='child'?'child':'adult',status:['pending','confirmed','declined'].includes(status)?status:'pending'}}
function familyFrom(g){if(Array.isArray(g.members))return{id:String(g.id||uid()),name:String(g.name||'Семья'),side:['marat','karina','common'].includes(g.side)?g.side:'common',table:String(g.table||''),phone:String(g.phone||''),notes:String(g.notes||''),members:g.members.map(m=>member(String(m.name||'Гость'),m.type,m.status)),createdAt:num(g.createdAt||Date.now())};let ms=[member(String(g.name||'Гость'),'adult',g.status)];for(let i=1;i<Math.max(1,Math.round(num(g.adults||1)));i++)ms.push(member('Взрослый '+(i+1),'adult',g.status));for(let i=0;i<Math.round(num(g.children));i++)ms.push(member('Ребёнок '+(i+1),'child',g.status));return{id:String(g.id||uid()),name:String(g.name||'Семья'),side:['marat','karina','common'].includes(g.side)?g.side:'common',table:String(g.table||''),phone:String(g.phone||''),notes:String(g.notes||''),members:ms,createdAt:num(g.createdAt||Date.now())}}
function normalize(raw){let b=defaultState();if(!raw||typeof raw!=='object')return b;return{version:4,settings:{couple:String(raw.settings&&raw.settings.couple||b.settings.couple),weddingDate:String(raw.settings&&raw.settings.weddingDate||b.settings.weddingDate),budget:num(raw.settings&&raw.settings.budget||b.settings.budget)},expenses:Array.isArray(raw.expenses)?raw.expenses.map(e=>({id:String(e.id||uid()),title:String(e.title||'Расход'),category:String(e.category||'Другое'),vendor:String(e.vendor||''),amount:num(e.amount),paid:Math.min(num(e.paid),num(e.amount)),due:String(e.due||''),notes:String(e.notes||''),done:!!e.done,createdAt:num(e.createdAt||Date.now())})):[],guests:Array.isArray(raw.guests)?raw.guests.map(familyFrom):[],purchases:Array.isArray(raw.purchases)?raw.purchases.map(p=>({id:String(p.id||uid()),title:String(p.title||'Покупка'),amount:num(p.amount),owner:String(p.owner||'Вместе'),due:String(p.due||''),purchased:!!p.purchased,createdAt:num(p.createdAt||Date.now())})):[],chat:Array.isArray(raw.chat)?raw.chat.map(m=>({id:String(m.id||uid()),author:m.author==='Карина'?'Карина':'Марат',text:String(m.text||''),createdAt:num(m.createdAt||Date.now())})).filter(m=>m.text):[],createdAt:num(raw.createdAt||Date.now())}}
function load(){try{return normalize(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'))}catch(e){return defaultState()}}
let state=load(),route='dashboard',openFamilies=new Set(),author=localStorage.getItem(AUTHOR_KEY)==='Карина'?'Карина':'Марат',sync={room:null,key:null,revision:0,timer:null,poll:null,applying:false};
function save(message){state.version=4;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();if(message)toast(message);schedulePush()}
function totals(){let ep=state.expenses.reduce((a,x)=>a+x.amount,0),paid=state.expenses.reduce((a,x)=>a+x.paid,0),pp=state.purchases.reduce((a,x)=>a+x.amount,0),pPaid=state.purchases.reduce((a,x)=>a+(x.purchased?x.amount:0),0),planned=ep+pp;return{budget:state.settings.budget,planned:planned,paid:paid+pPaid,debt:Math.max(0,planned-paid-pPaid),free:state.settings.budget-planned,progress:state.settings.budget?Math.min(100,planned/state.settings.budget*100):0}}
function guestTotals(){let all=0,confirmed=0,pending=0;state.guests.forEach(f=>f.members.forEach(m=>{all++;if(m.status==='confirmed')confirmed++;if(m.status==='pending')pending++}));return{all,confirmed,pending}}
function countdown(){let d=Math.ceil((new Date(state.settings.weddingDate+'T12:00:00')-new Date())/86400000);return d>0?d:0}
function navHtml(mobile){return['dashboard','expenses','guests','chat','purchases'].map(r=>'<button class="'+(route===r?'active ':'')+(mobile?'':'nav-btn')+'" data-route="'+r+'">'+icons[{dashboard:'home',expenses:'wallet',guests:'people',chat:'message',purchases:'check'}[r]]+'<span>'+(mobile?'<small>'+routes[r][0]+'</small>':'<span>'+routes[r][0]+'</span>')+'</span></button>').join('')}
function setupChrome(){document.documentElement.dataset.theme=localStorage.getItem(THEME_KEY)==='dark'?'dark':'light';$('#sideNav').innerHTML=navHtml(false);$('#mobileNav').innerHTML=navHtml(true);$('#settingsIcon').innerHTML=icons.settings;$('#themeBtn').innerHTML=document.documentElement.dataset.theme==='dark'?icons.sun:icons.moon;$('#shareBtn').innerHTML=icons.share;$('#addIcon').innerHTML=icons.plus}
function updateChrome(){$('#pageTitle').textContent=routes[route][0];$('#pageSubtitle').textContent=routes[route][1];$('#sideNav').innerHTML=navHtml(false);$('#mobileNav').innerHTML=navHtml(true);$('#addBtn').style.display=['chat','settings'].includes(route)?'none':'inline-flex'}
function dashboard(){let t=totals(),g=guestTotals(),urgent=state.expenses.filter(x=>x.amount>x.paid&&!x.done).slice(0,4);return'<div class="grid dashboard"><article class="card hero"><div><small>ОБЩИЙ БЮДЖЕТ</small><h2>'+money(t.budget).replace('₽','')+' <span>₽</span></h2><p>'+(t.free>=0?'Свободно '+money(t.free):'Превышение '+money(Math.abs(t.free)))+'</p></div><div class="metrics"><div class="metric"><small>Запланировано</small><b>'+money(t.planned)+'</b></div><div class="metric"><small>Оплачено</small><b>'+money(t.paid)+'</b></div><div class="metric"><small>Осталось</small><b>'+money(t.debt)+'</b></div></div></article><div class="side-stack"><article class="card countdown"><small>ДО СВАДЬБЫ</small><b>'+countdown()+'</b><span>дней</span></article><article class="card pad"><div class="section-head"><div><h3>Гости</h3><p>Семьи и подтверждения</p></div><button class="small-btn blue" data-route="guests">Открыть</button></div><div class="list">'+(state.guests.slice(0,3).map(f=>'<div class="row"><div class="row-icon">'+icons.people+'</div><div class="row-copy"><b>'+esc(f.name)+'</b><span>'+f.members.length+' человек</span></div><div class="row-value"><b>'+f.me`;